### PR TITLE
Add forward balancing

### PR DESCRIPTION
**Pull request by StessyMougeot**
Support multiple fluentD instance to forward logs

### CODE REVIEW

**Comment by sterchelen** [comment]
Maybe a bit of documentation? readme/changelog...

**Comment by StessyMougeot** [comment]
Sure, doc updated

**Review by sterchelen — APPROVED** [review]
👍🏼 🚀 🎉  **lgtm** 👍🏼 🚀 🎉

**Review by RymRabehi — APPROVED** [review]
lgtm

**Pull request merged**
